FACTURACIONCAJA/PetCenterFacturacionCaja/UPC.TP3.FacturacionCaja.Web/Areas/FacturacionCaja/Controllers/ComprobantePagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPC.TP3.Dominio.Entidades;
using UPC.TP3.FacturacionCaja.Negocio.CN;

namespace UPC.TP3.FacturacionCaja.Web.Areas.FacturacionCaja.Controllers
{
    public class ComprobantePagoController : Controller
    {
        // GET: FacturacionCaja/ComprobantePago
        public ActionResult Index()
        {
            List<ComprobantePago> comprobantepagos = new ComprobantePagoCN().GetComprobantePagos();
            ViewBag.comprobantepagos = comprobantepagos;
            return View();
        }

        // GET: FacturacionCaja/ComprobantePago/Details/5
        public ActionResult Details(int id)
        {
            ComprobantePago comprobantepago = new ComprobantePagoCN().GetComprobantePagoById(id);
            ViewBag.comprobantepago = comprobantepago;
            return View();
        }

        // GET: FacturacionCaja/ComprobantePago/Create
        public ActionResult Create()
        {
            List<Empleado> empleados = new EmpleadoCN().GetEmpleados();
            ViewBag.empleados = empleados;
            List<TurnoCaja> turnoCajas = new TurnoCajaCN().GetTurnoCajas();
            ViewBag.turnoCajas = turnoCajas;
            List<TipoMoneda> tipoMonedas = new TipoMonedaCN().GetTipoMonedas();
            ViewBag.tipoMonedas = tipoMonedas;

            return View();
        }

        // POST: FacturacionCaja/ComprobantePago/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            ComprobantePago comprobantePago = new ComprobantePago();

            
            comprobantePago.montoRecibido = Double.Parse(collection["comprobantePago.montoRecibido"]);
            comprobantePago.tipoComprobante = collection["comprobantePago.tipoComprobante"];
            comprobantePago.razonSocial = collection["comprobantePago.razonSocial"];
            comprobantePago.medioPago = collection["comprobantePago.medioPago"];
            comprobantePago.TipoMoneda_ID = int.Parse(collection["comprobantePago.TipoMoneda_ID"]);

            try
            {
                ViewBag.comprobantePago = new ComprobantePagoCN().InsertComprobantePago(comprobantePago);
                // TODO: Add update logic here
                return View();
            }
            catch (Exception e)
            {
                ViewBag.exception = e.Message;
                return View();
            }
        }

        // GET: FacturacionCaja/ComprobantePago/Edit/5
        public ActionResult Edit(int id)
        {
            //return View();
            return RedirectToAction("Index");
        }

        // POST: FacturacionCaja/ComprobantePago/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            return RedirectToAction("Index");

            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FacturacionCaja/ComprobantePago/Delete/5
        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
            return View();
        }

        // POST: FacturacionCaja/ComprobantePago/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            return RedirectToAction("Index");
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FACTURACIONCAJA/PetCenterFacturacionCaja/UPC.TP3.FacturacionCaja.Web/Areas/Mantenimientos/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPC.TP3.Dominio.Entidades;
using UPC.TP3.FacturacionCaja.Negocio.CN;

namespace UPC.TP3.FacturacionCaja.Web.Areas.Mantenimientos.Controllers
{
    public class EmpleadosController : Controller
    {
        // GET: Mantenimientos/Empleados
        public ActionResult Index()
        {
            List<Empleado> empleados = new EmpleadoCN().GetEmpleados();
            ViewBag.empleados = empleados;
            return View();
        }

        // GET: Mantenimientos/Empleados/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mantenimientos/Empleados/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mantenimientos/Empleados/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mantenimientos/Empleados/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Mantenimientos/Empleados/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mantenimientos/Empleados/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mantenimientos/Empleados/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FACTURACIONCAJA/PetCenterFacturacionCaja/UPC.TP3.FacturacionCaja.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema Integrado Pet Center</title>
    <link href="~/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("About", "Home", new { area = "" })"class="navbar-brand"><img src='@Url.Content("~/Content/images/logo.png")' alt="Sistema Integrado Pet Center" height="20" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home", new { area = "" })">Inicio</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Facturación y Caja <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Arqueo", new { area = "FacturacionCaja" })">Actualizar Arqueo</a></li>
                            <li><a href="@Url.Action("Index", "ComprobantePago", new { area = "FacturacionCaja" })">Actualizar Comprobante Pago</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mantenimientos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Empleados", new { area = "Mantenimientos" })">Turnos</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("About", "Home", new { area = "" })">Acerca de</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Miguel Concepción <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Cerrar sesión</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema Integrado Pet Center - UPC 2017-1 - Taller de Proyectos 3</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>